alias config="/usr/bin/git --git-dir=/home/rishi/.cfg/ --work-tree=/home/rishi"
alias n="nn -eaA"
alias updg="sudo apt update && sudo apt upgrade -y"
alias nv="nvim"
alias ls="lsd --group-directories-first"
alias s="kitty +kitten ssh"
alias lg="lazygit"
alias ncs="LD_LIBRARY_PATH=/home/rishi/Downloads/openssl-1.1.1u/ ncspot"
alias fnty="fc-cache -f -v"
